channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - nbserverproxy
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::panel
  - tornado 
  - jupyter-panel-proxy
